import { Router } from 'express';
import { z } from 'zod';
import { randomBytes } from 'crypto';
import { getDb } from '../db.js';
import { requireAuth, type AuthRequest } from '../middleware/auth.js';
import { requireRole } from '../middleware/rbac.js';
import { uid } from '../utils.js';
import { appPath, trialEndsAt, TRIAL_DAYS } from '../config/site.js';
import { ADMIN_EMAIL, sendMailReliable, smtpFrom } from '../services/email.js';

const router = Router();
const LOGIN_URL = appPath('/login');
const FOUNDER_URL = appPath('/founder');

function generateKeyCode(plan: string): string {
  const prefix = plan.toUpperCase().slice(0, 3);
  const rand = randomBytes(4).toString('hex').toUpperCase();
  return `CAFYZ-${prefix}-${rand}`;
}

// POST /api/licenses — founder generates a key
router.post('/', requireAuth, requireRole('founder'), async (req: AuthRequest, res, next) => {
  try {
    const data = z.object({
      plan:       z.enum(['basic','pro','premium']),
      expires_at: z.string().optional(),
      note:       z.string().optional(),
      quantity:   z.number().int().min(1).max(50).optional(),
      recipient_email: z.string().email().optional(),
      /** When true and no expires_at, defaults to the standard free-trial end date. */
      trial:      z.boolean().optional(),
    }).parse(req.body);

    const expiresAt = data.expires_at ?? (data.trial === true ? trialEndsAt() : null);

    const qty = data.quantity ?? 1;
    const created = [];
    for (let i = 0; i < qty; i++) {
      const id = uid();
      const keyCode = generateKeyCode(data.plan);
      await getDb().execute({
        sql: `INSERT INTO license_keys(id,key_code,plan,expires_at,note) VALUES(?,?,?,?,?)`,
        args: [id, keyCode, data.plan, expiresAt, data.note ?? null],
      });
      created.push({ id, key_code: keyCode, plan: data.plan, expires_at: expiresAt, note: data.note ?? null });
    }

    if (data.recipient_email) {
      const keysList = created.map(k => k.key_code).join('<br/>');
      await sendMailReliable({
        from: smtpFrom(true),
        to: data.recipient_email,
        replyTo: ADMIN_EMAIL,
        subject: `[Cafyz] Your ${data.plan.toUpperCase()} license key${created.length > 1 ? 's' : ''}`,
        html: `<p>Your Cafyz license key${created.length > 1 ? 's are' : ' is'} ready:</p>
               <p style="font-family:ui-monospace,Menlo,Consolas,monospace;font-size:14px;line-height:1.7">${keysList}</p>
               <p>Plan: <b>${data.plan.toUpperCase()}</b></p>
               <p>${data.trial ? `Free trial: <b>${TRIAL_DAYS} days</b>${expiresAt ? ` (ends ${new Date(expiresAt).toLocaleDateString('en-US', { timeZone: 'UTC' })})` : ''}` : 'License generated by founder.'}</p>
               <p>Login here: <a href="${LOGIN_URL}">${LOGIN_URL}</a></p>
               <p>Need help? Contact <a href="mailto:${ADMIN_EMAIL}">${ADMIN_EMAIL}</a>.</p>`,
      });
    }

    res.status(201).json(qty === 1 ? created[0] : created);
  } catch (e) { next(e); }
});

// GET /api/licenses — founder lists all keys
router.get('/', requireAuth, requireRole('founder'), async (_req, res, next) => {
  try {
    const rows = await getDb().execute(`
      SELECT lk.*, r.name as restaurant_name
      FROM license_keys lk
      LEFT JOIN restaurants r ON r.id = lk.restaurant_id
      ORDER BY lk.created_at DESC
    `);
    res.json(rows.rows);
  } catch (e) { next(e); }
});

// GET /api/licenses/mine — current restaurant's active license
router.get('/mine', requireAuth, async (req: AuthRequest, res, next) => {
  try {
    const rid = req.user!.restaurant_id;
    const [restRow, licRow] = await Promise.all([
      getDb().execute({ sql: 'SELECT plan FROM restaurants WHERE id=?', args: [rid] }),
      getDb().execute({
        sql: `SELECT * FROM license_keys WHERE restaurant_id=? AND is_active=1 ORDER BY activated_at DESC LIMIT 1`,
        args: [rid],
      }),
    ]);
    const license = (licRow.rows[0] ?? null) as Record<string, unknown> | null;
    const expiresAt = String(license?.expires_at ?? '');
    const expiryTs = expiresAt ? new Date(expiresAt).getTime() : Number.NaN;
    const trialExpired = Number.isFinite(expiryTs) ? expiryTs <= Date.now() : false;
    const daysLeft = Number.isFinite(expiryTs) ? Math.max(0, Math.ceil((expiryTs - Date.now()) / 86_400_000)) : null;
    res.json({
      plan:    restRow.rows[0]?.plan ?? 'basic',
      license,
      trial_expires_at: expiresAt || null,
      trial_expired: trialExpired,
      trial_days_left: daysLeft,
      purchase_url: appPath('/license'),
    });
  } catch (e) { next(e); }
});

// POST /api/licenses/activate — restaurant owner/manager activates a key
router.post('/activate', requireAuth, async (req: AuthRequest, res, next) => {
  try {
    const { key_code } = z.object({ key_code: z.string().min(1) }).parse(req.body);
    const rid = req.user!.restaurant_id;

    if (!['owner','manager'].includes(req.user!.role)) {
      res.status(403).json({ error: 'Only owners or managers can activate license keys.' });
      return;
    }

    const db = getDb();
    const row = await db.execute({
      sql: `SELECT * FROM license_keys WHERE key_code=? AND is_active=1 AND restaurant_id IS NULL`,
      args: [key_code.trim().toUpperCase()],
    });
    if (!row.rows.length) {
      res.status(400).json({ error: 'Invalid or already-used license key.' });
      return;
    }
    const key = row.rows[0] as Record<string, unknown>;

    // Check expiry
    if (key.expires_at && new Date(String(key.expires_at)) < new Date()) {
      res.status(400).json({ error: 'This license key has expired.' });
      return;
    }

    const now = new Date().toISOString();
    await db.execute({
      sql: `UPDATE license_keys SET restaurant_id=?, activated_at=? WHERE id=?`,
      args: [rid, now, String(key.id)],
    });
    await db.execute({
      sql: `UPDATE restaurants SET plan=? WHERE id=?`,
      args: [String(key.plan), rid],
    });

    const updated = await db.execute({ sql: 'SELECT plan FROM restaurants WHERE id=?', args: [rid] });
    res.json({ success: true, plan: updated.rows[0]?.plan, activated_at: now });
  } catch (e) { next(e); }
});

// POST /api/licenses/purchase-request — manager/owner requests a license purchase
router.post('/purchase-request', requireAuth, requireRole('owner', 'manager'), async (req: AuthRequest, res, next) => {
  try {
    const data = z.object({
      plan:  z.enum(['basic', 'pro', 'premium']),
      email: z.string().email().optional(),
      note:  z.string().max(500).optional(),
    }).parse(req.body);

    const rid = req.user!.restaurant_id;
    const db = getDb();
    const email = data.email ?? req.user!.email;

    const pending = await db.execute({
      sql: `SELECT id FROM license_purchase_requests WHERE restaurant_id=? AND status='pending' LIMIT 1`,
      args: [rid],
    });
    if (pending.rows.length) {
      res.status(409).json({ error: 'You already have a pending license request.' });
      return;
    }

    const rest = await db.execute({ sql: 'SELECT name FROM restaurants WHERE id=?', args: [rid] });
    const restaurantName = String(rest.rows[0]?.name ?? 'Restaurant');

    const id = uid();
    await db.execute({
      sql: `INSERT INTO license_purchase_requests(id,restaurant_id,requester_user_id,email,plan,note) VALUES(?,?,?,?,?,?)`,
      args: [id, rid, req.user!.id, email, data.plan, data.note ?? null],
    });

    await sendMailReliable({
      from: smtpFrom(true),
      to: ADMIN_EMAIL,
      subject: `[Cafyz] License purchase request — ${restaurantName} (${data.plan.toUpperCase()})`,
      html: `<p><b>${restaurantName}</b> requested a <b>${data.plan.toUpperCase()}</b> license.</p>
             <p><b>Contact email:</b> ${email}</p>
             ${data.note ? `<p><b>Note:</b> ${data.note}</p>` : ''}
             <p>Fulfill in <a href="${FOUNDER_URL}">Founder Panel → License Requests</a>.</p>`,
    });

    res.status(201).json({ id, status: 'pending', plan: data.plan, email });
  } catch (e) { next(e); }
});

// GET /api/licenses/purchase-requests/mine — restaurant's license requests
router.get('/purchase-requests/mine', requireAuth, requireRole('owner', 'manager'), async (req: AuthRequest, res, next) => {
  try {
    const rows = await getDb().execute({
      sql: `SELECT id,plan,email,status,note,created_at,fulfilled_at FROM license_purchase_requests
            WHERE restaurant_id=? ORDER BY created_at DESC LIMIT 20`,
      args: [req.user!.restaurant_id],
    });
    res.json(rows.rows);
  } catch (e) { next(e); }
});

// DELETE /api/licenses/:id — founder revokes a key
router.delete('/:id', requireAuth, requireRole('founder'), async (req, res, next) => {
  try {
    await getDb().execute({
      sql: `UPDATE license_keys SET is_active=0 WHERE id=?`,
      args: [String(req.params.id)],
    });
    res.status(204).end();
  } catch (e) { next(e); }
});

export default router;
